version: '3.4'
services:

  sc-postgres:
    container_name: sc-postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data


volumes:
  postgres-volume:
    name: sc-postgres 
  logs-volume:
    name: sc-logs

networks:
  sc:
